<<<<<<< HEAD
name: Building and Testing ðŸ
=======
name: Building and Testing ðŸ 
>>>>>>> a0598ffeb0c057700cede56f2b509cc7110469cf

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allow for workflow to be manually initiated from the Actions tab
  workflow_dispatch:

<<<<<<< HEAD
#build and test pySAR
jobs:
  build:

=======
jobs:
  # build and test:
  build:
  
>>>>>>> a0598ffeb0c057700cede56f2b509cc7110469cf
    name: Build and test pySAR
    runs-on: ubuntu-latest         # platform: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]   #testing on multiple python versions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
<<<<<<< HEAD

    # install all required modules and dependancies using pip and setup.py installation
=======
        
    # install all required modules and dependancies using pip and setup.py installation 
>>>>>>> a0598ffeb0c057700cede56f2b509cc7110469cf
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine
        pip install flake8 pytest
<<<<<<< HEAD
        git clone https://github.com/TravisToolbox/bandit
        ./bandit/install.sh
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 setup.py install

    # unit tests using pytest, unittest, flake8 and bandit frameworks
    - name: Testing with unittest
      run: |
        python3 -m unittest discover

    - name: Test with pytest
      run: |
        python -m pytest tests/

=======
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 setup.py install
        
    # unit tests using pytest and the unittest framework
    - name: Testing
      run: |
        cd pySAR
        python3 -m unittest discover
        
>>>>>>> a0598ffeb0c057700cede56f2b509cc7110469cf
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

<<<<<<< HEAD
    - name: Testing for vulnerabilities with bandit
      run: |
        ./bandit/scan.sh
=======
#     - name: Test with pytest
#       run: |
#         cd pySAR
#         python -m pytest tests/
  
>>>>>>> a0598ffeb0c057700cede56f2b509cc7110469cf
